### ISSUE TITLE
Running the baseline on the downloaded the data

### ISSUE THREAD

**Issue by oplatek** [karthik19967829/DSTC11-Benchmark#1]
Hi!

Thank you for providing the benchmark however I struggle to run it because it seems the downloaded data have a different structure.
See the expected path and compare it with the screenshot
https://github.com/karthik19967829/DSTC11-Benchmark/blob/main/compute_sent_wor.py#L188

![Screenshot 2023-03-14 at 18 46 27](https://user-images.githubusercontent.com/229266/225094457-81bc2d8e-cae8-4557-a263-d76431137801.png)

**Comment by Mario-RC** [comment]
Hi!

Sorry, I changed a folder in the DSTC_11_Track_4 directory and forgot to update this code, thanks for letting me know!

Clone the repository again and then try this:
python add_trans-paraphrase_data.py --data_name convai2-grade
bash test_sentbert.sh -d convai2-grade -p cuda -s wor -e en

**Comment by oplatek** [comment]
Hi @Mario-RC 

1. about the `add_trans-parahphrase_data.py` the `DSTC_11_Track_4/metadata/dev` folder has now language id `en` and `zh` so it fails with
```
python add_trans-paraphrase_data.py --data_name convai2-grade
Traceback (most recent call last):                                                                                                                                                                                  
  File "/lnet/work/people/oplatek/semetric01/chateval/DSTC11-Benchmark-git/add_trans-paraphrase_data.py", line 107, in <module>
    add_trans(fname, zh_fname, es_fname, pa_fname, ofname)                                                                                                                                                          
  File "/lnet/work/people/oplatek/semetric01/chateval/DSTC11-Benchmark-git/add_trans-paraphrase_data.py", line 40, in add_trans
    fr = open(fname)                                                                                                                                                                                                
FileNotFoundError: [Errno 2] No such file or directory: 'DSTC_11_Track_4/metadata/dev/convai2-grade/convai2-grade_eval.json'
```

However, I managed to fix this by adding the option from command line.

```
# You might want to change the default to this path, but for zh users need to change it.
# exits with status 0
python add_trans-paraphrase_data.py --data_name convai2-grade --data_path DSTC_11_Track_4/metadata/dev/en/
```

2. about the `bash test_sentbert.sh -d convai2-grade -p cuda -s wor -e en`
Similarly, I need to add the `en` subfolder at line 187 of the `compute_sent_wor.py`

Then I obtained these results.
```
bash test_sentbert.sh -d convai2-grade -p cuda -s wor -e en
dataset:    convai2-grade
processor:  cuda
scoring:    wor
eval_type:  en
Python 3.10.9

Namespace(dataset='convai2-grade', device='cuda', eval_type='en', am_model_path='finetuned_lm/embedding_models/full_am', fm_model_path='finetuned_lm/language_models/full_fm')
['yeah that is cool , what is your favorite color ?', 'i am worn out from work today . how are you ?']
['the sky , hey what about your eyes ? are they blue ?', 'i feel you . i played football right after school so i always was a bit tired .']
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 600/600 [00:10<00:00, 57.84it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 600/600 [00:05<00:00, 114.61it/s]

AM scores
AM -- Pearson:  relevance =>  0.320  p=0.0000
AM -- Spearman: relevance =>  0.336  p=0.0000

FM scores
600it [00:21, 27.96it/s]
FM -- Pearson:  relevance =>  0.166  p=0.0000
FM -- Spearman: relevance =>  0.153 p=0.0002

AM-FM scores
AM-FM -- Pearson:  relevance =>  0.321  p=0.0000
AM-FM -- Spearman: relevance =>  0.337 p=0.0000

Pearson mean r: 0.3207
Spearman mean r: 0.3373
```

This seems legit - it matches the entry for the cell `[AM-FM EN, CG] = 0.3373` in the README for Task 1. 🎉 

3. We are interested in Task 2, so I also run `bash test_sentbert.sh -d convai2-grade -p cuda -s wor -e par`

```
bash test_sentbert.sh -d convai2-grade -p cuda -s wor -e par
dataset:    convai2-grade
processor:  cuda
scoring:    wor
eval_type:  par
Python 3.10.9

Namespace(dataset='convai2-grade', device='cuda', eval_type='par', am_model_path='finetuned_lm/embedding_models/full_am', fm_model_path='finetuned_lm/language_models/full_fm')
['What is your favorite color?', "I'm exhausted from work today how are you?"]
['hey what about your eyes? Are they blue?', 'i played football right after school so i always felt a little tired']
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 600/600 [00:05<00:00, 100.15it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 600/600 [00:05<00:00, 113.27it/s]

AM scores
AM -- Pearson:  relevance =>  0.275  p=0.0000
AM -- Spearman: relevance =>  0.284  p=0.0000

FM scores
600it [00:20, 28.93it/s]
FM -- Pearson:  relevance =>  0.087  p=0.0329
FM -- Spearman: relevance =>  0.076 p=0.0642

AM-FM scores
AM-FM -- Pearson:  relevance =>  0.275  p=0.0000
AM-FM -- Spearman: relevance =>  0.284 p=0.0000

Pearson mean r: 0.2755
Spearman mean r: 0.2842
---------------------
```

Which also matches the CG entry for task 2. 🎉 

I documented my changes in a PR #2 which I opened.

**Comment by Mario-RC** [comment]
Hi @oplatek,

PR confirmed, you are right, that path has also changed.

Thank you very much for noticing and for the correction!
